---
title: "class_work"
author: "Joslyn Fritz"
date: "5/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```


```{r}

#' Power Required by Speed
#'
#' This function determines the power required to keep a vehicle moving at
#' a given speed
#' @param cdrag coefficient due to drag default=0.3
#' @param crolling coefficient due to rolling/friction default=0.015
#' @param v vehicle speed (m/2)
#' @param m vehicle mass (kg)
#' @param A area of front of vehicle (m2)
#' @param g acceleration due to gravity (m/s) default=9.8
#' @param pair (kg/m3) default =1.2
#' @return power (W) 


autopower = function(V, m, A, cdrag=0.3, crolling=0.015, pair=1.2,g=9.8){
P = crolling*m*g*V + 1/2*A*pair*cdrag*V**3
return(P)
} 

autopower(V=30,m=31752,A=2.5)
  
```
Answer is 152,176.3

### Steps for running your model over multiple inputs
1. design a data structure to store results
2. generate the input data
3. apply to the model

Example: imagine we want to see how much power is generated given


```{r}
nsample = 100
speeds = rnorm(mean=25, sd=4, n=nsmaple)

results$power = autopower(V=results$speed, A=25, m=2000)

# Always plot your data to make sure it makes sense

ggplot(results, aes(x="Across Speed", y=power/1000))=geom_boxplot()


possible_cars = data.frame

possible_cars$power = autopower((V=speed_base, A = possible_cars$area, m=possible_cars$area))

# sample - tool in R to sample from a distrubition and allows you to set the bondaries. 

whichcar = base::sample(possible_cars$row, size=nsample, prob=possible_cars=prob, replace=TRUE)
# This is exactly like bootstrapping!

```



